basePath: /
definitions:
  dto.Subscription:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  dto.SumSubscriptionsRequest:
    properties:
      end_date:
        type: string
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  dto.SumSubscriptionsResponse:
    properties:
      total:
        type: integer
    type: object
  dto.UpdateSubscription:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for managing user online subscriptions
  title: Online Subscriptions API
  version: "1.0"
paths:
  /subscriptions:
    post:
      consumes:
      - application/json
      description: Create a new subscription
      parameters:
      - description: Subscription info
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/dto.Subscription'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create subscription
      tags:
      - subscriptions
  /subscriptions/{userUUID}:
    delete:
      description: Delete an existing subscription by user UUID
      parameters:
      - description: User UUID
        in: path
        name: userUUID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid UUID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete subscription by user UUID
      tags:
      - subscriptions
    get:
      description: Get subscription for a user by UUID
      parameters:
      - description: User UUID
        in: path
        name: userUUID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Subscription'
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Subscription not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get subscription by user UUID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Update an existing subscription by user UUID
      parameters:
      - description: User UUID
        in: path
        name: userUUID
        required: true
        type: string
      - description: Update data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateSubscription'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update subscription by user UUID
      tags:
      - subscriptions
  /subscriptions/filter:
    post:
      consumes:
      - application/json
      description: Get subscriptions matching filter criteria
      parameters:
      - description: Filter parameters
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/dto.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Subscription'
            type: array
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: No subscriptions found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List subscriptions by filter
      tags:
      - subscriptions
  /subscriptions/sum:
    post:
      consumes:
      - application/json
      description: Get total price of subscriptions for user/service/period
      parameters:
      - description: Filter parameters
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/dto.SumSubscriptionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SumSubscriptionsResponse'
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get sum of subscriptions
      tags:
      - subscriptions
schemes:
- http
swagger: "2.0"
